export const types = {
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  ADD_EMPLOYEE: "ADD_EMPLOYEE",
  EDIT_EMPLOYEE: "EDIT_EMPLOYEE",
  REMOVE_EMPLOYEE: "REMOVE_EMPLOYEE",
  SET_WEATHER: "SET_WEATHER",
  SET_LOADING: "SET_LOADING",
  SET_USER: "SET_USER"
};
