export const employeeData = [
  {
    name: "Samantha Welsh",
    position: "teacher",
    age: 25,
    hireDate: "01/20/2014",
    skills: ["leadership", "annoying", "kind of cute"],
    salary: 35000,
  },
  {
    name: "AJ Broman",
    position: "teacher",
    age: 25,
    hireDate: "02/10/2016",
    skills: ["not a cook", "cool af", "cuter than sam"],
    salary: 35000,
  },
  {
    name: "Denice Hargan",
    position: "teacher",
    age: 35,
    hireDate: "11/24/2017",
    skills: ["leadership", "sweet", "star wars fanatic"],
    salary: 36000,
  },
  {
    name: "Sheila Meila",
    position: "teacher",
    age: 30,
    hireDate: "10/20/2016",
    skills: ["teacher", "annoying", "nerdy"],
    salary: 25000,
  },
  {
    name: "Sheila Jewlisha",
    position: "teacher",
    age: 30,
    hireDate: "05/13/2010",
    skills: ["teacher", "annoying", "nerdy"],
    salary: 99000,
  },
  {
    name: "Turango Mango",
    position: "teacher",
    age: 62,
    hireDate: "10/20/2016",
    skills: ["teacher", "annoying", "nerdy"],
    salary: 25000,
  },
  {
    name: "Samantha Welsh",
    position: "teacher",
    age: 25,
    hireDate: "01/20/2014",
    skills: ["leadership", "annoying", "kind of cute"],
    salary: 35000,
  },
  {
    name: "AJ Broman",
    position: "teacher",
    age: 25,
    hireDate: "02/10/2016",
    skills: ["not a cook", "cool af", "cuter than sam"],
    salary: 35000,
  },
  {
    name: "Denice Hargan",
    position: "teacher",
    age: 35,
    hireDate: "11/24/2017",
    skills: ["leadership", "sweet", "star wars fanatic"],
    salary: 36000,
  },
  {
    name: "Sheila Meila",
    position: "teacher",
    age: 30,
    hireDate: "10/20/2016",
    skills: ["teacher", "annoying", "nerdy"],
    salary: 25000,
  },
  {
    name: "Sheila Jewlisha",
    position: "teacher",
    age: 30,
    hireDate: "05/13/2010",
    skills: ["teacher", "annoying", "nerdy"],
    salary: 99000,
  },
  {
    name: "Turango Mango",
    position: "teacher",
    age: 62,
    hireDate: "10/20/2016",
    skills: ["teacher", "annoying", "nerdy"],
    salary: 25000,
  },
];
